config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "grams#index"
  resources :grams, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :comments, only: [:create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gram
  belongs_to :user
end

app/models/gram.rb
class Gram < ApplicationRecord
  validates :message, presence: true
  validates :image, presence: true

  mount_uploader :image, GramUploader

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :grams
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def render_not_found(status=:not_found)
    render plain: "#{status.to_s.titleize}", status: status
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def create
    @gram = Gram.find_by_id(params[:gram_id])
    return render_not_found if @gram.blank?
    @gram.comments.create(comment_params.merge(user: current_user))
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy, :update]

  def index
    @grams = Gram.all
  end

  def show
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
  end

  def new
    @gram = Gram.new
  end

  def create
    @gram = current_user.grams.create(gram_params)
    if @gram.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
  end

  def update
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:unauthorized) if @gram.user != current_user
    @gram.update(gram_params)
    if @gram.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:unauthorized) if @gram.user != current_user
    @gram.destroy
    redirect_to root_path
  end
  private

  def gram_params
    params.require(:gram).permit(:image, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/views/grams/edit.html.erb
<h1>Let's edit the gram</h1>

<%= simple_form_for @gram do |f| %>
  <%= f.input :message %>
  <%= f.submit %>
<% end %>

app/views/grams/index.html.erb
<div class="col-12 row justify-content-center ml-auto mr-auto">
  <% @grams.each do |gram| %>
  <div class="card col-12 col-sm-6 col-md-4 col-lg-3 col-xl-2 ml-auto mr-auto">
    <div class="handle"><%= gram.user.email %></div>
    <%= image_tag gram.image, class: 'img-fluid' %>
    <p>
      <%= gram.message %>
    </p>
  </div>
  <% end %>
</div>

app/views/grams/new.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">
<h1>Let's create a new gram</h1>

<%= simple_form_for @gram do |f| %>
  <%= f.input :image %>
  <%= f.input :message %>
  <%= f.submit "Post!", class: 'btn btn-primary' %>
<% end %>

</div>

app/views/grams/show.html.erb
<h1>Show me the gram</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grammable</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
    <div class="top-nav">
      <div class="col-10 ml-auto mr-auto">
	<div class="brand float-left">
	  Grammable
	</div>
	<div class="add float-right">
	  <% if current_user %>
	    Welcome, <%= current_user.email %>.
	    <%= link_to "New Post", new_gram_path %>
	    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
	  <% else %>
	    <%= link_to "Sign In", new_user_session_path %>
	    <%= link_to "Sign Up", new_user_registration_path %>
	  <% end %>
	</div>
      </div>
      <br class="clear-fix" />
    </div>

    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>